const users = [
  {
    id: 1,
    firstName: 'Fisrt 1',
    lastName: 'Last 1',
    userName: 'u1',
    profile: 'driver',
    status: true,
    email: 'u1@test.com',
    phone: '(11)1111-1111',
    celular: '(11)11111-1111',
    password: '',
    confirmPassword: '',
    company: 'company1',
    expire: 'no',
    dateExpire: '',
  },
  {
    id: 2,
    firstName: 'First 2',
    lastName: 'Last 2',
    userName: 'u2',
    profile: 'driver',
    status: true,
    email: 'u2@test.com',
    phone: '(11)1111-1111',
    celular: '(11)11111-1111',
    password: '',
    confirmPassword: '',
    company: 'company2',
    expire: 'no',
    dateExpire: '',
  },
  {
    id: 3,
    firstName: 'First 3',
    lastName: 'Last 3',
    userName: 'u3',
    profile: 'driver',
    status: true,
    email: 'u3@test.com',
    phone: '(11)1111-1111',
    celular: '(11)11111-1111',
    password: '',
    confirmPassword: '',
    company: 'company1',
    expire: 'no',
    dateExpire: '',
  },
  {
    id: 4,
    firstName: 'First 4',
    lastName: 'Last 4',
    userName: 'u4',
    profile: 'driver',
    status: true,
    email: 'u4@test.com',
    phone: '(11)1111-1111',
    celular: '(11)11111-1111',
    password: '',
    confirmPassword: '',
    company: 'company2',
    expire: 'no',
    dateExpire: '',
  },
];
export default users;
